### ISSUE TITLE
About an alternative implementation of MaskedCnn

### ISSUE THREAD

**Issue by AlexFuster** [singh-hrituraj/PixelCNN-Pytorch#1]
About the masked CNN implementation, If we don't consider channels, but just spatial locations, wouldn't be the same to just put all the padding at the top and left of the image?

For example, imagine a 3x3 convolution where a zero padding of 1 is usually used at each side for keeping the image size. The idea is that, if you concentrate the whole horizontal padding in the top side (2 padding) and the whole vertical one in the left side (2 padding), you are implementing a masked convolution of type B, as you are predicting the pixel in the bottom right corner of the filter.

The masked convolution of type A would be exactly the same but setting the bottom right corner of the filter to 0.

Let me your thoughts about this implementation

**Comment by singh-hrituraj** [comment]
Hi Alex

From what I understand, you are saying that instead of explicitly making the weights of the convolution operation zero, we can just pad the left and top border of the image. In this manner, the values of the pixels where the multiplication of weight matrix happens will be as follows for a ` 3 X 3 ` convolution:

```
|  PAD | PAD | PAD | 
|  PAD | PAD | PAD |
|  PAD | PAD | VAL |
```
The above distribution means, we are basically calculating the value of pixel designated ` VAL `  from the information available to us.

However, this is little different from the original paper in some manner. Let us consider a pixel somewhere in the middle of the image.  As per your method, we will be taking pixels on the top and left of the pixel which we are trying to predict. As we keep going deeper into the network, the field of view for this pixel will increase. It will keep expanding to the left and top but not to the right. Thus, ideally what it should be covering is supposed to be like this:
![CNN Field of View](https://github.com/singh-hrituraj/PixelCNN-Pytorch/blob/master/images/Sequence.png?raw=true)

However, the field of view will get blocked to only the top and left side pixels. 

I hope I was able to understand your question. Cheers!

**Comment by AlexFuster** [comment]
Hi, Singh,

Thanks for your answer, I made it up and tried it with one layer, but I didn't notice that effect when stacking multiple ones.

best regards
